# SPDX-FileCopyrightText: Copyright (c) 2024-2025 Yegor Bugayenko
# SPDX-License-Identifier: MIT
---
AllCops:
  Exclude:
    - 'bin/**/*'
    - 'assets/**/*'
    - 'vendor/**/*'
  DisplayCopNames: true
  TargetRubyVersion: 3.2
  SuggestExtensions: false
  NewCops: enable
require:
  - rubocop-minitest
  - rubocop-performance
  - rubocop-rake
Minitest/EmptyLineBeforeAssertionMethods:
  Enabled: false
Metrics/ParameterLists:
  Enabled: false
Style/GlobalVars:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Gemspec/RequiredRubyVersion:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false
Layout/MultilineMethodCallIndentation:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Metrics/ClassLength:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false
Metrics/PerceivedComplexity:
  Enabled: false
Layout/EmptyLineAfterGuardClause:
  Enabled: false
Layout/CaseIndentation:
  Enabled: false
Naming/MethodParameterName:
  MinNameLength: 2
Layout/EndOfLine:
  EnforcedStyle: lf
Layout/MultilineAssignmentLayout:
  Enabled: true
Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent
